export const FETCH_REVIEW_REQUEST = "FETCH_REVIEW_REQUEST" as const;
export const FETCH_REVIEW_SUCCESS = "FETCH_REVIEW_SUCCESS" as const;
export const FETCH_REVIEW_FAILURE = "FETCH_REVIEW_FAILURE" as const;
